/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormValidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormValidFeedback']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MessageCreationInput: typeof import('./src/components/MessageCreationInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MessageOutput: typeof import('./src/components/MessageOutput.vue')['default']
  }
}
